name: Release Drafter

on:
  push:
    branches:
      - acceptance
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  autolabeler:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        with:
          config-name: nerds-and-company/t3-release-drafter:release-drafter-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  draft_acceptance:
    if: github.ref == 'refs/heads/acceptance'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: nerds-and-company/t3-release-drafter:release-drafter-acceptance.yml
          commitish: acceptance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  draft_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: nerds-and-company/t3-release-drafter:release-drafter-main.yml
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
